server:
  port: 8086

spring:
  application:
    name: reconciliation-service

banking:
  account-service:
    base-url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
