server:
  port: 8081

spring:
  application:
    name: account-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/banking_platform}
    username: ${SPRING_DATASOURCE_USERNAME:banking}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

banking:
  jwt-secret: ${BANKING_JWT_SECRET}
  seed-admin-password: ${BANKING_SEED_ADMIN_PASSWORD}
  seed-admin-pin: ${BANKING_SEED_ADMIN_PIN}
  grpc:
    port: 9090
