server:
  port: 8081

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_platform
    username: banking
    password: banking
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

banking:
  jwt-secret: "dev-only-change-me-dev-only-change-me"
  grpc:
    port: 9090
